package com.endava.commands.enums;

public enum CommandType {
  CREATEAIRPLANE,
  CREATECAR,
  CREATESHIP,
  CREATETRAIN,
  CREATECOURSE,
  CREATERENT,
  CREATEAIRPLANEPARKING,
  CREATEBUSPARKING,
  CREATECARPARKING,
  CREATETRAINPARKING,
  CREATEPARKINGTICKET,
  EXITPARKING,
  LISTVEHICLES,
  LISTCOURSES,
  LISTRENTS,
  LISTPARKINGS,
  LISTPARKINGTICKETS,
  ADDPARKING,
  ADDPARKINGTICKETS,
  REMOVEPARKINGTICKET,
  SORTVEHICLESBYLOADCAPACITY,
  SORTVEHICLESBYPRICE,
  FILTERVEHICLESBYTYPE;
}
